export const OFFER= {
  MIN_PRICE: 500,
  MAX_PRICE: 2000,
  FIRST_WEEK_DAY: 1,
  LAST_WEEK_DAY: 7,
  MIN_RATING: 1,
  MAX_RATING: 6,
  MIN_ROOMS: 1,
  MAX_ROOMS: 8,
  MIN_GUESTS: 1,
  MAX_GUESTS: 10,
  MIN_COMMENTS: 0,
  MAX_COMMENTS: 100,
}
